// Angular
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/http';
import '@angular/router';
// RxJS
import 'rxjs';
// Bootstrap
import '../public/css/app.css';
import '../public/css/bootstrap-theme.min.css';
import '../public/font-awesome/css/font-awesome.min.css';